---
plugin: gcp_compute
keyed_groups:
- prefix: gcp
key: labels.awx_role
groups:
"{{ item }}": "'{{ item }}' in labels.awx_role"
zones:
- us-central1-a
- us-central1-b
- us-central1-c
- us-central1-f
- us-east4-a
- us-east4-b
- us-east4-c
- us-east4-d
projects:
- PROJECT_ID
hostnames:
- name
auth_kind: serviceaccount
compose:
ansible_host: networkInterfaces[0].networkIP
